### PR TITLE
Python code test

### PR DESCRIPTION
**Pull request by mrchucho**
This is my attempt a Python version of platform-code-test. The code itself is basically identical to the Ruby code. The tests are a little different.

I looked for a Python rspec alternative and found [mamba](https://github.com/nestorsalceda/mamba). It's similar to rspec. However, it's not quite as robust as rspec (from a nesting/lazy evaluation standpoint). More importantly, I'm not sure it's as popular and well-known in Python's community as rspec is in Ruby's. Pytest, while more of a unit testing framework, seems to be the de facto testing framework. Basically I made a test case for each of the award _types_ then a parameterized set of inputs and expected values. So, those, in a sense, constitute the "test cases".

Anyway, I'm open to suggestions, corrections, etc.

### CODE REVIEW

**Comment by mrchucho** [comment]
All the tests pass except the one that is marked "pending" in rspec (i.e. the one covered by this code test):

Screen Shot 2020-03-10 at 11 08 48 AM

**Comment by dolinsky** [comment]
Neat! If you're wanting a standalone rspec alternative, [behave](https://github.com/behave/behave) gets the most standalone love, and for integration with pytest there's [pytest-bdd](https://github.com/pytest-dev/pytest-bdd). I went through your pipenv instructions. They worked for me and I was able to execute the tests.

**Comment by mrchucho** [comment]
Thanks for the feedback & suggestions.

> If you're wanting a standalone rspec alternative, [behave](https://github.com/behave/behave) gets the most standalone love, and for integration with pytest there's [pytest-bdd](https://github.com/pytest-dev/pytest-bdd).

I checked out behave. It seems a little closer to cucumber than to rspec. But definitely worth considering. May re-evaluate once we get a better sense of what our candidates are expecting.

> I went through your pipenv instructions. They worked for me and I was able to execute the tests.

Excellent! Thank you, 👍

**Comment by wbajzek** [comment]
Looks good to me. I haven't used python in 20 years but I was able to understand it just fine.

**Pull request merged**
